module.exports = {
  'up': `CREATE TABLE Booking (
    Id bigint(20) NOT NULL AUTO_INCREMENT,
    UserId bigint(20) NOT NULL,
    UserDeviceId int(11) DEFAULT NULL,
    ProviderId bigint(20) DEFAULT NULL,
    RideTypeId int(11) DEFAULT NULL,
    FromLocation varchar(255) DEFAULT NULL,
    ToLocation varchar(255) DEFAULT NULL,
    CancelledFor varchar(255) DEFAULT NULL,
    SourceLat decimal(10,6) DEFAULT NULL,
    SourceLong decimal(10,6) DEFAULT NULL,
    DestinyLat decimal(10,6) DEFAULT NULL,
    DestinyLong decimal(10,6) DEFAULT NULL,
    S2CellId varchar(20) DEFAULT NULL,
    Status varchar(45) DEFAULT NULL,
    Distance int(11) DEFAULT NULL,
    Estimation decimal(10,2) DEFAULT NULL,
    CurrencyType longtext CHARACTER SET utf8 COLLATE utf8_general_ci,
    Tax decimal(10,2) DEFAULT NULL,
    WaitingCharges int(11) DEFAULT NULL,
    TotalAmount decimal(10,2) DEFAULT NULL,
    Description varchar(255) DEFAULT NULL,
    OutletName varchar(255) DEFAULT NULL,
    ContactNo varchar(15) DEFAULT NULL,
    CountryId int(11) DEFAULT NULL,
    CancelledBy varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    RideName varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    VehicleName varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    ProviderEarning decimal(10,2) DEFAULT NULL,
    TotalEarning decimal(10,2) DEFAULT NULL,
    PaymentMode varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'cash',
    CardId varchar(255) DEFAULT NULL,
    IsActive varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'yes',
    ProviderRejectedIds json DEFAULT NULL,
    IsUserReviewed varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'no',
    IsCouponApplied varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'no',
    RedeemedId int(11) DEFAULT NULL,
    DiscountAmount decimal(10,2) DEFAULT NULL,
    CouponCode varchar(50) DEFAULT NULL,
    BookingType varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'now',
    SeatCount int(11) DEFAULT NULL,
    EmailStatus varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'no',
    IsPool varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'no',
    BookingTimestamp timestamp NULL DEFAULT NULL,
    CreateAt timestamp DEFAULT CURRENT_TIMESTAMP,
    UpdateAt timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    outletId varchar(255) DEFAULT NULL,
    netAmount DOUBLE(10,2) DEFAULT NULL,
    orderReferenceId varchar(255) DEFAULT NULL,
    orderStatus varchar(255) DEFAULT NULL,
    deliverycharge DOUBLE(10,2) DEFAULT NULL,
    deliveryAddressId INT(11) DEFAULT NULL,
    firstMile varchar(45) DEFAULT '0',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,                
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    eta timestamp NULL DEFAULT NULL,
    Type varchar(11) DEFAULT 'taxi',
    serviceCommission INT(11) DEFAULT '0',
    ServiceCategoryId INT(11) DEFAULT NULL,
    ServiceSubCategoryId INT(11) DEFAULT NULL,
    ServiceGroupId INT(11) DEFAULT NULL,
    ServiceStatuLogs JSON DEFAULT NULL,
    ServiceTimeSlot JSON DEFAULT NULL,
    ServiceStartImage varchar(255) DEFAULT NULL,
    ServiceEndImage varchar(255) DEFAULT NULL,
    ServiceIds JSON DEFAULT NULL,
    ServiceAddons JSON DEFAULT NULL,
    markReady TINYINT(4) DEFAULT NULL,
    deliveryStartTimeSlot timestamp NULL DEFAULT NULL,
    deliveryEndTimeSlot timestamp NULL DEFAULT NULL,
    prescriptionimageUrl varchar(1000) DEFAULT NULL,
    confirmedTime timestamp NULL DEFAULT NULL,
    isRated varchar(45) DEFAULT 'NOTRATED',
    orderSuggestions varchar(255) DEFAULT NULL,
    PRIMARY KEY (Id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8`,
  'down': 'DROP TABLE Booking'
}
