module.exports = {
    'up': `CREATE TABLE Outlets (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  restaurantId int(10) unsigned NOT NULL,
  email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  password varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  image varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  isPureVeg tinyint(4) NOT NULL,
  costForTwo float(10,3) NOT NULL,
  isExculsive tinyint(12) DEFAULT NULL,
  isOfferAvailable tinyint(4) NOT NULL DEFAULT '0',
  preparationTime tinyint(25) DEFAULT NULL,
  deliveryCharges decimal(10,2) DEFAULT '20.00',
  addressLineOne varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  addressLineTwo varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  street varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  area varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  city varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  state varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  country varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  zipcode varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  latitude decimal(10,6) DEFAULT NULL,
  longitude decimal(10,6) DEFAULT NULL,
  s2CellId varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  s2key char(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  contactNumber varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  restaurantCommission double(10,2) DEFAULT NULL,
  status int(11) DEFAULT '1',
  existLogin int(11) NOT NULL DEFAULT '1',
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  totalAmount decimal(10,2) DEFAULT '0.00',
  balanceAmount decimal(10,2) DEFAULT '0.00',
  serviceCommission int(11) DEFAULT '0',
  averageRating int(11) DEFAULT '0',
  isBlocked int(11) DEFAULT '0',
  deviceToken varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  os varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  type varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT '0',
  packingCharge int(11) DEFAULT '0',
  cuisine varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '[]',
  PRIMARY KEY (id),
  KEY outlets_restaurantid_index (restaurantId),
  CONSTRAINT outlets_restaurantid_foreign FOREIGN KEY (restaurantId) REFERENCES Restaurant (id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    'down': 'DROP TABLE Outlets'
}